/** POPULAR MOVIES [START] */

export const POPULAR_START = 'POPULAR_START';
export const POPULAR_FAIL = 'POPULAR_FAIL';
export const POPULAR_SUCCESS = 'POPULAR_SUCCESS';

/** POPULAR MOVIES [END] */
