/** POPULAR MOVIES [START] */

export const POPULAR_START = 'POPULAR_START';
export const POPULAR_FAIL = 'POPULAR_FAIL';
export const POPULAR_SUCCESS = 'POPULAR_SUCCESS';

/** POPULAR MOVIES [END] */

/** GENRES [START] */

export const GENRES_START = 'GENRES_START';
export const GENRES_FAIL = 'GENRES_FAIL';
export const GENRES_SUCCESS = 'GENRES_SUCCESS';

/** GENRES [END] */

/** MOVIE [START] */

export const MOVIE_START = 'MOVIE_START';
export const MOVIE_FAIL = 'MOVIE_FAIL';
export const MOVIE_SUCCESS = 'MOVIE_SUCCESS';

/** MOVIE [END] */

/** SIMILAR MOVIES [START] */

export const SIMILAR_START = 'SIMILAR_START';
export const SIMILAR_FAIL = 'SIMILAR_FAIL';
export const SIMILAR_SUCCESS = 'SIMILAR_SUCCESS';

/** SIMILAR MOVIES [END] */

/** SEARCH [START] */

export const SEARCH_START = 'SEARCH_START';
export const SEARCH_FAIL = 'SEARCH_FAIL';
export const SEARCH_SUCCESS = 'SEARCH_SUCCESS';

/** SEARCH [END] */
